In [22]:
%load_ext autoreload
%autoreload 2
import sys
import matplotlib.pyplot as plt
import numpy as np
import cv2

sys.path.append("..")
from cv.locator import DroneLocator, ButtonFinder
from cv import locator
from cv.dewarp import dewarp
import os

recal_paths="../../../../Downloads/recalibrating"
recal_imgs=(
    [
        os.path.join(recal_paths, name) 
        for name in os.listdir(recal_paths)
    ]

)

imgs_path = "../imgs/m4/"
landing_preds_path = os.path.join(imgs_path, "landing_det")
landing_pad_imgs = (
    [
        os.path.join(landing_preds_path, name) 
        for name in os.listdir(landing_preds_path)
    ]
)

gantry_preds_path = os.path.join(imgs_path, "end_offsets")
gantry_imgs = (
    [
        os.path.join(gantry_preds_path, name) 
        for name in os.listdir(gantry_preds_path)
    ]
)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [32]:
qr_locator = locator.QRLocator()
circle_locator = locator.CircleLocator()
for img in gantry_imgs:
    img = plt.imread(img)
    print("===================")
    print(qr_locator.find(img))
    print(circle_locator.find(img))

(False, (0, 0))
[[ 660. 1006.   36.]]
(True, array([788.25, 683.25]))
[[782. 954.  45.]]
(False, (0, 0))
[]
(True, array([968.75, 585.5 ]))
[[972. 860.  48.]]
(True, array([1146.5,  672.5]))
[[1150.  940.   48.]]
(True, array([1173.5 ,  695.75]))
[[1134.  960.   46.]]
(True, array([870. , 769.5]))
[[ 912. 1038.   43.]]
(False, (0, 0))
[[528. 940.  35.]]
(True, array([969.5, 859.5]))
[]
(False, (0, 0))
[]
(False, (0, 0))
[[978. 468.  46.]]
(False, (0, 0))
[]
(False, (0, 0))
[]
(False, (0, 0))
[]
(True, array([1060.,  674.]))
[[1064.  946.   46.]]
(True, array([969.5 , 497.25]))
[[968. 762.  49.]]
(True, array([877.5 , 679.75]))
[[876. 956.  43.]]
(True, array([1149.5 ,  763.25]))
[[1152. 1028.   43.]]
(False, (0, 0))
[]
(True, array([970.  , 769.25]))
[[ 970. 1042.   44.]]
(False, (0, 0))
[[1282.  994.   42.]]
(True, array([695.5 , 807.25]))
[]
(True, array([767.  , 697.75]))
[[806. 968.  42.]]
(True, array([1099. ,  592.5]))
[[1062.  858.   47.]]
(True, array([968.25, 675.75]))
[[970. 

In [34]:
pose = locator.CircleQRPoseEstimator(linreg_path="../cv/offset_model.pkl")
for img in gantry_imgs:
    img = plt.imread(img)
    print("===================")
    print(pose(img))

0.76
